name: Download Data and Render pdf file
on:
  repository_dispatch:
    types: render-cv
  push:
    branches:
      - master

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: |
         chmod +x ./main.sh
         ./main.sh
      shell: bash
