name: Download Data and Render pdf file
on:
  repository_dispatch:
    types: render-cv
  push:
    branches:
      - master

env:
  USE_CACHE: true
  ETL_FOLDER: download-and-convert-gdocs
  TEX_FOLDER: my-awesome-cv

jobs:
  Get-Docker-Images-and-Compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Update Config files
      run: |
        cd $ETL_FOLDER
        mkdir -p configs
        echo "${{ secrets.CREDENTIALS }}" > configs/credentials.json
        echo "${{ secrets.DOCUMENT_ID }}" > configs/document_id.json
        cd ..
      shell: bash

    - name: Build image
      run: |
         cd $ETL_FOLDER
         docker build -t gdocs .
         cd ..
      shell: bash

    - name: Pull Image
      run: |
        docker pull thomasweise/docker-texlive-thin
      shell: bash

    - name: Print echo
      run: |
        docker images
      shell: bash

    - name: Download Google Docs Document
      run: |
        docker run --name etl_python --rm -i -t -w "/app" -v "$PWD":/app gdocs python3 $ETL_FOLDER/main.py
      shell: bash

