name: Download Data and Render pdf file
on:
  repository_dispatch:
    types: render-cv
    inputs:
      gDocsID:
        description: 'Google Docs File ID'     
        required: true
        default: 'secrets.DOCUMENT_ID'
  push:
    branches:
      - master

env:
  USE_CACHE: true
  ETL_FOLDER: download-and-convert-gdocs
  TEX_FOLDER: my-awesome-cv

jobs:
  Get-Docker-Images-and-Compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Output Inputs
      run: echo "${{ toJSON(github.event.inputs) }}"

    - name: Update CREDENTIALS Config file
      id: create-json-1
      uses: jsdaniell/create-json@v1.2.1
      with:
        name: "credentials.json"
        json: ${{ secrets.CREDENTIALS }}
        dir: '${{ env.ETL_FOLDER }}/configs/'

    - name: Update DOCUMENT_ID Config file
      id: create-json-2 
      uses: jsdaniell/create-json@v1.2.1
      with:
        name: "document_id.json"
        json: ${{ secrets.DOCUMENT_ID }}
        dir: '${{ env.ETL_FOLDER }}/configs/'
          
    - name: Build image
      run: |
         cd $ETL_FOLDER
         docker build -t gdocs .
         cd ..
      shell: bash

    - name: Pull Image
      run: |
        docker pull thomasweise/docker-texlive-thin
      shell: bash

    - name: Download Google Docs Document
      run: |
        docker run --name etl_python --rm -i -w "/app" -v "$PWD":/app gdocs python3 $ETL_FOLDER/main.py
      shell: bash

    - name: Complie XeLaTex Document
      run: |
        cd $TEX_FOLDER
        docker run --rm --user $(id -u):$(id -g) -i -w "/doc" -v "$PWD":/doc thomasweise/docker-texlive-thin make
      shell: bash

    - name: Archive code cv.pdf
      uses: actions/upload-artifact@v3
      with:
        name: zipped_cv
        path: ${{ env.TEX_FOLDER }}/cv/cv.pdf
        retention-days: 1

